### ISSUE TITLE
[Samplers] Allow for more than one span_kind

### ISSUE THREAD

**Issue by dol** [open-telemetry/opentelemetry-java-contrib#1940]
### Component(s)

samplers

### Is your feature request related to a problem? Please describe.

The declarative configuration RuleBasedRoutingSampler currently only supports defining multiple rules. But this rules only apply for one `span_kind`.

In a Spring boot application application typically the actuator endpoint will be dropped by the sampler. In addition some background tasks (`span_kind=Internal`) should also be dropped.
Currently this is not possible at the moment

```yaml
  sampler:
    parent_based:
      root:
        rule_based_routing:
          fallback_sampler:
            always_on:
          span_kind: SERVER # Should be defined on the rules level
          rules:
            # Drop spans where url.path matches the regex /actuator.* (i.e. spring boot actuator endpoints).
            - action: DROP
              attribute: url.path
              pattern: /actuator.*
            # Drop some async database lookups, span_kind=Internal
            - action: DROP
              attribute: db.sql.table
              pattern: ACT_RU_JOB
```

### Describe the solution you'd like

Introduce a set of rules to allow for more samplers.

```yaml
  sampler:
    parent_based:
      root:
        rule_based_routing:
          fallback_sampler:
            always_on:
          rule_sets:
            - span_kind: SERVER
              rules:
              # Drop spans where url.path matches the regex /actuator.* (i.e. spring boot actuator endpoints).
              - action: DROP
                attribute: url.path
                pattern: /actuator.*
            - span_kind: Internal
              rules:
              - action: DROP
                attribute: db.sql.table
                pattern: ACT_RU_JOB
```

### Describe alternatives you've considered

It similar to the https://github.com/open-telemetry/opentelemetry-configuration/issues/102 proposal.
