### ISSUE TITLE
Add support for cli params/custom label in groovy script

### ISSUE THREAD

**Issue by jatan28** [open-telemetry/opentelemetry-java-contrib#33]
Currently, when you are trying to monitor the JVM metrics for multiple processes/applications on a single host, it is impossible to differentiate which process the metrics originated from.
Having support for adding custom labels to the groovy script through command line params or a config would provide the required flexibility to re-use the same groovy script to solve the problem stated above and also give end users the option to add more labels.
Example 
```
 jmx:
 jmx/service1:
  jar_path: /home/jajmera/opentelemetry-java-contrib-jmx-metrics-0.0.1-SNAPSHOT.jar
  endpoint: localhost:9050
  target_system: jvm
  custom_lables: 
     <label-key>: <label-value>
  collection_interval: 10s
```

OR 
```
 jmx:
 jmx/service1:
  jar_path: /home/jajmera/opentelemetry-java-contrib-jmx-metrics-0.0.1-SNAPSHOT.jar
  endpoint: localhost:9050
  groovy_script: test.groovy --labels [<key>:<value>, ...]
  collection_interval: 10s
```
