### ISSUE TITLE
JMX gatherer with wildfly - "WARNING: No valid value(s) for wildfly.request.count ..."

### ISSUE THREAD

**Issue by hecomp** [open-telemetry/opentelemetry-java-contrib#384]
**Description**
A clear and concise description of what the bug is or observed behavior.
The JMX Metric Gatherer is throwing warnings for listener metric `wildfly.request.count`.

**Steps to reproduce**
Provide a (runnable) recipe for reproducing the error.
See the following example PR. 
[Wildfly Example](https://github.com/lightstep/opentelemetry-examples/pull/111)

**Expectation**
A clear and concise description of what you expected to see.
The expectation is JMX gatherer scraping/gathering Wildfly metrics properly for each metric. 

**What applicable config did you use?**
Config: (e.g. the yaml config file)
```
receivers:
  jmx/wildfly:
      jar_path: /opt/opentelemetry-jmx-metrics.jar
      endpoint: wildfly:19990
      target_system: jvm,wildfly
      collection_interval: 5s
```
The following PR has a complete concise info.
[Wildfly Example](https://github.com/lightstep/opentelemetry-examples/pull/111)

**Relevant Environment Information**
Version: (e.g., `v0.0.1`, `2bef20a`, etc.)
OS: (e.g., "Ubuntu 20.04")
Compiler (if manually compiled): (e.g., "openJDK 1.8.0_252")
`jboss/wildfly:23.0.1.Final`

**Additional context**
```otel-collector    | 2022-07-06T22:39:17.024Z	debug	subprocess/subprocess.go:288	WARNING: No valid value(s) for wildfly.request.count - io.opentelemetry.contrib.jmxmetrics.MBeanHelper@196d0b57.requestCount	{"kind": "receiver", "name": "jmx/wildfly", "pipeline": "metrics"}```
