### ISSUE TITLE
[Maven Extension] Failed to export spans FRAME_SIZE_ERROR: 4740180

### ISSUE THREAD

**Issue by slankka** [open-telemetry/opentelemetry-java-contrib#523]
**Description**
I'm using `opentelemetry-maven-extension` to collect metrics.

Opentelemetry deployment:
[jaegertracing/jaeger/tree/main/docker-compose/monitor](https://github.com/jaegertracing/jaeger/tree/main/docker-compose/monitor)

When I execute `mvn verify -Dotel.traces.exporter=otlp -Dotel.exporter.otlp.endpoint="http://<host>:4317" `

here are outputs:
```
13, 2022 11:25:14 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
Failed to export spans. The request could not be executed. Full error message: Broken pipe (Write failed)

13, 2022 11:25:24 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
Failed to export spans. The request could not be executed. Full error message: null

13, 2022 11:25:54 PM io.opentelemetry.sdk.internal.ThrottlingLogger log
Too many log messages detected. Will only log once per minute from now on.
13, 2022 11:25:54 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
Failed to export spans. The request could not be executed. Full error message: FRAME_SIZE_ERROR: 4740180
13, 2022 11:25:54 PM io.opentelemetry.sdk.trace.SdkTracerProvider shutdown
Calling shutdown() multiple times.
```

**Steps to reproduce**
full docker-compose files:
[jaeger.tar.gz](https://github.com/open-telemetry/opentelemetry-java-contrib/files/9778330/jaeger.tar.gz)

1. `docker-compose up -d`
2. download `opentelemetry-maven-extension-1.18.0-alpha.jar` and save to MAVEH_HOME/lib/ext/
3. `mvn verify -Dotel.traces.exporter=otlp -Dotel.exporter.otlp.endpoint="http://<host>:4317" `

**Expectation**
opentelemetry-maven-extension reports metrics to otel successfully.

**What applicable config did you use?**
Config: please look at attachments.

**Relevant Environment Information**
Version: ('1.10.0-alpha', '1.18.0-alpha')
OS: (docker-compose runs on "CentOS 7", maven runs on my macbook pro 2017)
Docker: (CentOS,  Version: 20.10.12)
Docker-compose: (1.18.0)

**Additional context**
Quick view in my docker-compose.yml
```
...
services:
  jaeger:
    networks:
      - backend
    image: jaegertracing/all-in-one:latest
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    ports:
      - "14250:14250"
      - "14268:14268"
      - "6831:6831/udp"
      - "16686:16686"
      - "16685:16685"
  otel_collector:
    networks:
      - backend
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - "./otel-collector-config.yml:/etc/otel-collector-config.yml"
    command: ["--config=/etc/otel-collector-config.yml"]
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
      - "14278:14278"
      - "65535:65535"
    depends_on:
      - jaeger
...
```
