### ISSUE TITLE
[jmx-metrics] Metrics Gatherer reports old data if target becomes unavailable

### ISSUE THREAD

**Issue by dehaansa** [open-telemetry/opentelemetry-java-contrib#910]
### Component(s)

jmx-metrics

## Description
When monitoring a JMX target with the JMX metrics gatherer, if that target becomes unresponsive or unavailable the most recently collected metrics continue to report via the configured exporter as if they are new metrics.

## Steps to Reproduce
Start a simple java executable like the following
```
cat <<EOF > hello.java
class Sleepy {
  public static void main(String args[]) throws InterruptedException {
    while (true) {
      Thread.sleep(10000);
    }
  }
}
EOF
javac hello.java

java -ea -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 Sleepy > /dev/null 2>&1 &
```

Configure the JMX Metric gatherer to monitor said target.
```
otel.jmx.service.url = service:jmx:rmi:///jndi/rmi://localhost:9010/jmxrmi
otel.jmx.target.system = jvm
otel.jmx.interval.milliseconds = 5000
otel.jmx.remote.registry.ssl=false
otel.metrics.exporter = prometheus
otel.exporter.prometheus.host = localhost
otel.exporter.prometheus.port = 4317
```

After seeing metrics collected at the prometheus endpoint, then stop the Sleepy java process. Observe that the metrics are still reported (with fresh timestamps) at the prometheus endpoint.

While the prometheus endpoint would make some sense to continue to show old data points (with correct timestamps), the real use case where this issue was encountered was utilizing the jmx receiver in opentelemetry-collector-contrib, where we would not expect old, duplicate metrics to be exported via OTLP and sent to the receiver. To observe that behavior, the jmx receiver would be configured like the following (note - the receiver can only be used with a released version of the JMX Metrics gatherer, or the collector must be built with special build flags to allow use of a non-released version):

```
exporters:
  file:
    path: ./output.json
receivers:
  jmx:
    collection_interval: 5s
    endpoint: localhost:9010
    jar_path: /path/to/opentelemetry-java-contrib-jmx-metrics.jar
    target_system: jvm
service:
  pipelines:
    metrics:
      exporters:
        - file
      receivers:
        - jmx
```

## Expected Result
Metrics would at minimum not be reported with new timestamps, but preferably metrics would not be reported _at all_ for times where the monitoring target was unavailable

## Actual Result
The most recently collected value continues to be reported for any instruments, with a fresh timestamp attached.

### Component version

First observed w/ 1.14.0, but has been seen w/ latest
